### ISSUE TITLE
Imported ontologies do not load in Noble Mentions

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#11]
Whether an ontology is online or a local file, Noble Mentions will not load and add items from imported ontology into the terminology files.

For a local version of an imported ontology...

loading nlpBreastCancer ontology .. edu.pitt.dbmi.nlp.noble.ontology.IOntologyException: Unable to create ontology http://ontologies.dbmi.pitt.edu/deepphe/toy/nlpBreastCancerInstances.owl
	at edu.pitt.dbmi.nlp.noble.ontology.owl.OOntology.createOntology(OOntology.java:341)
	at edu.pitt.dbmi.nlp.noble.mentions.model.DomainOntology.<init>(DomainOntology.java:127)
	at edu.pitt.dbmi.nlp.noble.ui.NobleMentionsTool$8.run(NobleMentionsTool.java:494)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://ontologies.dbmi.pitt.edu/deepphe/toy/nlpCancer.owl> Cause: http://ontologies.dbmi.pitt.edu/deepphe/toy/nlpCancer.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1322)
	at org.coode.owlapi.owlxmlparser.OWLImportsHandler.endElement(OWLImportsHandler.java:69)
	at org.coode.owlapi.owlxmlparser.OWLXMLParserHandler.endElement(OWLXMLParserHandler.java:1176)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
	at org.coode.owlapi.owlxmlparser.OWLXMLParser.parse(OWLXMLParser.java:96)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:216)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:868)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:806)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:821)
	at edu.pitt.dbmi.nlp.noble.ontology.owl.OOntology.createOntology(OOntology.java:333)
	... 3 more
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: http://ontologies.dbmi.pitt.edu/deepphe/toy/nlpCancer.owl
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:224)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:868)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:779)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1281)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1315)
	... 23 more
Caused by: java.io.FileNotFoundException: http://ontologies.dbmi.pitt.edu/deepphe/toy/nlpCancer.owl
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:217)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:169)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:259)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:123)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:216)
	... 27 more
Caused by: java.io.FileNotFoundException: http://ontologies.dbmi.pitt.edu/deepphe/toy/nlpCancer.owl
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:141)
	... 30 mo

**Comment by tseytlin** [comment]
OK. The above error had to do with messed up URIs..
After URIs were fixed and adding a local file IRI mapper, the issue has been resolved
