### ISSUE TITLE
Failed to import Metathesaurus

### ISSUE THREAD

**Issue by trivedigaurav** [dbmi-pitt/nobletools#32]
Trying to import UMLS terminologies from RRF files gives the following error:

```
Saving Term Information ...
Loading terms into datastructure ...
Saving Word Information ...
Loading MRDEF.RRF file ...
Loading MRSTY.RRF file ...
Loading MRREL.RRF file ...
Finding Root Concepts ...
Creating a Blacklist of High Frequency Words ...
total words: 1461905, frequent words (> 100): 27785, cutoff: 0.002
top words: 2923, super top words: 292, cutoff: 0.1
java.lang.NullPointerException
	at org.apache.jdbm.HTreeBucket.addElement(HTreeBucket.java:151)
	at org.apache.jdbm.HTreeDirectory.put(HTreeDirectory.java:222)
	at org.apache.jdbm.HTreeDirectory.put(HTreeDirectory.java:217)
	at org.apache.jdbm.HTreeDirectory.put(HTreeDirectory.java:217)
	at org.apache.jdbm.HTree.put(HTree.java:167)
	at java.util.AbstractMap.putAll(AbstractMap.java:281)
	at edu.pitt.dbmi.nlp.noble.util.JDBMMap.putAll(JDBMMap.java:222)
	at edu.pitt.dbmi.nlp.noble.util.ConceptImporter.loadRRF(ConceptImporter.java:1314)
	at edu.pitt.dbmi.nlp.noble.ui.TerminologyImporter.load(TerminologyImporter.java:861)
	at edu.pitt.dbmi.nlp.noble.ui.TerminologyImporter.execute(TerminologyImporter.java:399)
	at edu.pitt.dbmi.nlp.noble.ui.TerminologyImporter.access$2500(TerminologyImporter.java:75)
	at edu.pitt.dbmi.nlp.noble.ui.TerminologyImporter$2.run(TerminologyImporter.java:376)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tseytlin** [comment]
Can you tell me which version of UMLS you were using and what were the settings. Did you filter by sources or semantic types? I need that info to replicate the issue.

**Comment by trivedigaurav** [comment]
I am using the 2016AB-active and here's my config file https://pastebin.com/iwMCBHeE
