### ISSUE TITLE
NullPointerException on seemingly random texts

### ISSUE THREAD

**Issue by oersted** [dbmi-pitt/nobletools#36]
I keep getting NullPointerExceptions with select pieces of text. As far as I know there is no option to skip such cases and I cannot figure out what is the text feature that is making Noble crash.

This is the stacktrace I always get. It doesn't happen immediately, on my last attempt for example it failed with the sample number 362, after having processed the rest.

```
processing report (362) DOI-10.1002$$$cbin.10347.txt ... Exception in thread "main" java.lang.NullPointerException
	at java.util.StringTokenizer.<init>(StringTokenizer.java:199)
	at java.util.StringTokenizer.<init>(StringTokenizer.java:221)
	at edu.pitt.dbmi.nlp.noble.tools.TextTools.getWords(TextTools.java:359)
	at edu.pitt.dbmi.nlp.noble.coder.model.Mention.getMentions(Mention.java:208)
	at edu.pitt.dbmi.nlp.noble.tools.AcronymDetector.process(AcronymDetector.java:199)
	at edu.pitt.dbmi.nlp.noble.coder.NobleCoder.process(NobleCoder.java:366)
	at edu.pitt.dbmi.nlp.noble.coder.NobleCoder.process(NobleCoder.java:325)
	at edu.pitt.dbmi.nlp.noble.coder.NobleCoder.process(NobleCoder.java:303)
	at edu.pitt.dbmi.nlp.noble.ui.NobleCoderTool.process(NobleCoderTool.java:1567)
	at edu.pitt.dbmi.nlp.noble.ui.NobleCoderTool.main(NobleCoderTool.java:149)
```

Here are some sample texts that failed, they are all similar abstracts.

```
We have demonstrated that selected growth factors are involved in regulating survival and proliferation of progenitor cells derived from the neonatal rat organ of Corti (OC). The protective and regenerative effects of these defined growth factors on the injured organ of Corti were therefore investigated. The organ of Corti dissected from the Wistar rat pups (P3-P5) was split into apical, middle, and basal parts, explanted and cultured with or without neomycin and growth factors. Insulin-like growth factor-1 (IGF-1), fibroblast growth factor-2 (FGF-2), and epidermal growth factor (EGF) protected the inner hair cells (IHCs) and outer hair cells (OHCs) from neomycin ototoxicity. Using EGF, IGF-1, and FGF-2 alone induced no protective effect on the survival of auditory hair cells. Combining 2 growth factors (EGF + IGF-1, EGF + FGF-2, or IGF-1 + FGF-2) gave statistically protective effects. Similarly, combining all three growth factors effectively protected auditory hair cells from the ototoxic insult. None of the growth factors induced regeneration of hair cells in the explants injured with neomycin. Thus various combinations of the three defined factors (IGF-1, FGF-2, and EGF) can protect the auditory hair cells from the neomycin-induced ototoxic damage, but no regeneration was seen. This offers a possible novel approach to the treatment of hearing loss.
```

```
The modification of implant surface situated in the area of peri-implant sulcus has important role in bacterial and cell adhesion. Six different chemically and physically modified titanium discs were prepared: glazed (Tis-MALP), unglazed (Tis-O), unglazed and alkali-etched (Tis-OA), unglazed and coated with ZrN (Tis-OZ), unglazed, sand blasted, and acid etched (Tis-OPAE), and unglazed, sand blasted, acid, and alkali etched (Tis-OPAAE). Analysis of surface topography was determined using scanning electron microscopy and atomic force microscopy (AFM). Biocompatibility of gingival fibroblasts was characterized by the production of tumor necrosis factor alpha, collagen I, matrix metalloproteinase 2 (MMP-2) after 24 and 72 h and expression of α3 β1 integrin and vinculin using enzyme-linked immunosorbent assay (ELISA) or modified ELISA after 6 and 24 h. Microorganism adhesion (five bacterial strains) and biofilm formation was also evaluated. The adhesion of bacteria and gingival fibroblasts was significantly higher on titanium disc Tis-OPAAE and biofilm formation on the same surface for Streptococcus mutans, Streptococcus gordonii, and Streptococcus intermedius. The gingival fibroblasts on Tis-OPAAE disc had also significantly lower production of MMP-2. The collagen production was significantly lower on all surfaces with roughness higher than 0.2 μm. This study confirmed that the titanium disc with the surface roughness 3.39 μm (Tis-OPAAE) supported the adhesion of bacterial strains as well as gingival fibroblasts.
```

```
The aims of this study are to establish a time point to determine the most beneficial time to administer GCEE post incident to reduce oxidative damage and second, by using redox proteomics, to determine if GCEE can readily suppress 3-NT modification in TBI animals. By using a moderate traumatic brain injury model with Wistar rats, it is hypothesized that the role of 3-nitrotyrosine (3-NT) formation as an intermediate will predict the involvement of protein nitration/nitrosation and oxidative damage in the brain. In this experiment, the levels of protein carbonyls, 4-hydroxynonenal, and 3-nitrotyrosine were significantly elevated in TBI injured, saline treated rats compared with those who sustained an injury and were treated with 150 mg/kg of the glutathione mimetic, GCEE. Determining the existence of elevated 3-NT levels provides insight into the relationship between the protein nitration/nitrosation and the oxidative damage, which can determine the pathogenesis and progression of specific neurological diseases.
```

**Comment by oersted** [comment]
I just noticed that the issue is with the `AcronymDetector`, I just disabled `-acronymExpansion` and the issue went away. I still think it is worth looking into.
