### ISSUE TITLE
String index out of range Exception

### ISSUE THREAD

**Issue by tseytlin** [dbmi-pitt/nobletools#6]
Error: String index out of range: -2
Sentence: Ki-67% 20%/1849
Label: 67%/1852
processing report (280) patient10_report056_NOTE.txt ... 89 ms
processing report (281) patient10_report057_NOTE.txt ... 38 ms
processing report (282) patient10_report058_NOTE.txt ... 43 ms
processing report (283) patient10_report059_NOTE.txt ... 89 ms
processing report (284) patient10_report060_NOTE.txt ... 61 ms
processing report (285) patient10_report061_NOTE.txt ... 34 ms
Error: String index out of range: -3
Sentence: Multiple black round gallstones are present aggregating to 1.2 x 1.2 x 0.3 cm (ranging from 0.2 x 0.1 x 0.1 cm to 0.3 x 0.2 x 0.2 cm)./1748
Label: 1.2 x 1.2 x 0.3/1808
Error: String index out of range: -3
Sentence: Multiple black round gallstones are present aggregating to 1.2 x 1.2 x 0.3 cm (ranging from 0.2 x 0.1 x 0.1 cm to 0.3 x 0.2 x 0.2 cm)./1748
Label: 0.3 x 0.2 x 0.2/1863
processing report (286) patient10_report062_NOTE.txt ... 95 ms
Error: String index out of range: -2
Sentence: Ki-67% 20%/1267
Label: 67%/1270
processing report (287) patient10_report063_NOTE.txt ... 61 ms
processing report (288) patient10_report064_NOTE.txt ... 83 ms
Error: String index out of range: -2
Sentence: Ki-67% 20%/1360
Label: 67%/1363
processing report (289) patient10_report065_RAD.txt ... 37 ms
processing report (290) patient10_report066_RAD.txt ... 45 ms
processing report (291) patient10_report067_RAD.txt ... 45 ms
processing report (292) patient11_report001_NOTE.txt ... 131 ms
processing report (293) patient11_report001_SP.txt ... 59 ms
processing report (294) patient11_report004_RAD.txt ... 34 ms
processing report (295) patient11_report005_SP.txt ... 80 ms
processing report (296) patient11_report007_RAD.txt ... 19 ms
processing report (297) patient11_report008_PGN.txt ... 74 ms
Error: String index out of range: -1
Sentence: -was on IV vancomycin from 8/31/11 to 9/7/11/5326
Label: 9/7/5364
processing report (298) patient11_report009_RAD.txt ... 29 ms
processing report (299) patient11_report011_PGN.txt ... 32 ms
processing report (300) patient11_report016_RAD.txt ... 38 ms
processing report (301) patient11_report018_DS.txt ... 47 ms
processing report (302) patient11_report019_NOTE.txt ... 44 ms
processing report (303) patient11_report042_NOTE.txt ... 32 ms
processing report (304) patient11_report044_NOTE.txt ... 85 ms
processing report (305) patient12_report001_NOTE.txt ... 34 ms
processing report (306) patient12_report002_RAD.txt ... 51 ms
processing report (307) patient12_report003_SP.txt ... 88 ms
Error: String index out of range: -1
Sentence: BLANK-8 x 1     A/8290
Label: 8 x 1     /8296
Error: String index out of range: -1
Sentence: BLANK-7 x 1     A/8308
Label: 7 x 1     /8314
Error: String index out of range: -1
Sentence: BLANK-9 x 1     A/8326
Label: 9 x 1     /8332
Error: String index out of range: -1
Sentence: BLANK-3 x 1     A/8344
Label: 3 x 1     /8350
Error: String index out of range: -1
Sentence: BLANK-6 x 1     A/8362
Label: 6 x 1     /8368
Error: String index out of range: -1
Sentence: BLANK-5 x 1     A/8380
Label: 5 x 1     /8386
Error: String index out of range: -1
Sentence: BLANK-2 x 1     A/8398
Label: 2 x 1     /8404
Error: String index out of range: -1
Sentence: BLANK-1 x 1     A/8416
Label: 1 x 1     /8422
Error: String index out of range: -1
Sentence: BLANK-4 x 1     A/8434
Label: 4 x 1     /8440
Error: String index out of range: -2
Sentence: BLANK-10 x 1     A/8452Label:
10 x 1     /8458
Error: String index out of range: -1
Sentence: PAX-8 x 1     A/8829
Label: 8 x 1     /8833
Error: String index out of range: -1
Sentence: TTF-1 x 1     A/8888
Label: 1 x 1     /8892
processing report (308) patient12_report004_RAD.txt ... 76 ms
processing report (309) patient12_report005_NOTE.txt ... 131 ms
processing report (310) patient12_report006_NOTE.txt ... 17 ms
processing report (311) patient12_report007_NOTE.txt ... 109 ms
Error: String index out of range: -2
Sentence: Ki-67% 90%, very high/3213
Label: 67%/3216
processing report (312) patient12_report008_NOTE.txt ... 5 ms
processing report (313) patient12_report009_NOTE.txt ... 5 ms
processing report (314) patient12_report010_NOTE.txt ... 88 ms
Error: String index out of range: -2
Sentence: Ki-67% 90%, very high/2190
Label: 67%/2193
processing report (315) patient12_report011_RAD.txt ... 35 ms
processing report (316) patient12_report012_RAD.txt ... 20 ms
processing report (317) patient12_report013_SP.txt ... 98 ms
processing report (318) patient12_report014_PGN.txt ... java.lang.UnsupportedOperationException
at java.util.AbstractList.add(AbstractList.java:148)
at java.util.AbstractList.add(AbstractList.java:108)
at edu.pitt.dbmi.nlp.noble.tools.AcronymDetector.process(AcronymDetector.java:160)
at edu.pitt.dbmi.nlp.noble.coder.NobleCoder.process(NobleCoder.java:366)
at edu.pitt.dbmi.nlp.noble.coder.NobleCoder.process(NobleCoder.java:325)
at edu.pitt.dbmi.nlp.noble.coder.NobleCoder.process(NobleCoder.java:303)
at edu.pitt.dbmi.nlp.noble.ui.NobleCoderTool.process(NobleCoderTool.java:1567)
at edu.pitt.dbmi.nlp.noble.ui.NobleCoderTool$12.run(NobleCoderTool.java:1211)
at java.lang.Thread.run(Thread.java:745)

**Comment by tseytlin** [comment]
This is an issue with overlapping annotations during visualization. It is just a warning that I print when I encounter an overlapping span that can mess up my document. I can simply get rid of this warning

**Comment by tseytlin** [comment]
This system out has no harm was done on purpose, but throws people off. 
So I'll just hide it from view
